[2023-05-04T14:06:48.549+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: gsc_to_bq.ingest_dado scheduled__2023-05-03T00:00:00+00:00 [queued]>
[2023-05-04T14:06:48.585+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: gsc_to_bq.ingest_dado scheduled__2023-05-03T00:00:00+00:00 [queued]>
[2023-05-04T14:06:48.610+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-04T14:06:48.618+0000] {taskinstance.py:1280} INFO - Starting attempt 9 of 10
[2023-05-04T14:06:48.621+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-04T14:06:48.704+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): ingest_dado> on 2023-05-03 00:00:00+00:00
[2023-05-04T14:06:48.729+0000] {standard_task_runner.py:55} INFO - Started process 381 to run task
[2023-05-04T14:06:48.736+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'gsc_to_bq', 'ingest_dado', 'scheduled__2023-05-03T00:00:00+00:00', '--job-id', '742', '--raw', '--subdir', 'DAGS_FOLDER/gcs_to_bq.py', '--cfg-path', '/tmp/tmpbnxschjq']
[2023-05-04T14:06:48.741+0000] {standard_task_runner.py:83} INFO - Job 742: Subtask ingest_dado
[2023-05-04T14:06:48.888+0000] {task_command.py:388} INFO - Running <TaskInstance: gsc_to_bq.ingest_dado scheduled__2023-05-03T00:00:00+00:00 [running]> on host 1630dcf67789
[2023-05-04T14:06:49.175+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Junior Lafuente
AIRFLOW_CTX_DAG_ID=gsc_to_bq
AIRFLOW_CTX_TASK_ID=ingest_dado
AIRFLOW_CTX_EXECUTION_DATE=2023-05-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=9
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-03T00:00:00+00:00
[2023-05-04T14:06:50.034+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/gcs_to_bq.py", line 30, in ingest_dados
    import openpyxl
ModuleNotFoundError: No module named 'openpyxl'
[2023-05-04T14:06:50.059+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=gsc_to_bq, task_id=ingest_dado, execution_date=20230503T000000, start_date=20230504T140648, end_date=20230504T140650
[2023-05-04T14:06:50.080+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 742 for task ingest_dado (No module named 'openpyxl'; 381)
[2023-05-04T14:06:50.113+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-05-04T14:06:50.147+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
