[2023-03-05T01:30:00.435+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: teste_dag.nvalido scheduled__2023-03-04T23:30:00+00:00 [queued]>
[2023-03-05T01:30:00.453+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: teste_dag.nvalido scheduled__2023-03-04T23:30:00+00:00 [queued]>
[2023-03-05T01:30:00.453+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-05T01:30:00.454+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2023-03-05T01:30:00.455+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-05T01:30:00.478+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): nvalido> on 2023-03-04 23:30:00+00:00
[2023-03-05T01:30:00.487+0000] {standard_task_runner.py:55} INFO - Started process 296 to run task
[2023-03-05T01:30:00.493+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'teste_dag', 'nvalido', 'scheduled__2023-03-04T23:30:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/teste_dag.py', '--cfg-path', '/tmp/tmput4pzqpa']
[2023-03-05T01:30:00.494+0000] {standard_task_runner.py:83} INFO - Job 27: Subtask nvalido
[2023-03-05T01:30:00.622+0000] {task_command.py:388} INFO - Running <TaskInstance: teste_dag.nvalido scheduled__2023-03-04T23:30:00+00:00 [running]> on host 3d4e7c789958
[2023-03-05T01:30:00.818+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=teste_dag
AIRFLOW_CTX_TASK_ID=nvalido
AIRFLOW_CTX_EXECUTION_DATE=2023-03-04T23:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-04T23:30:00+00:00
[2023-03-05T01:30:00.833+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-05T01:30:00.835+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "echo 'quantidade não ok'"]
[2023-03-05T01:30:00.879+0000] {subprocess.py:86} INFO - Output:
[2023-03-05T01:30:00.890+0000] {subprocess.py:93} INFO - quantidade não ok
[2023-03-05T01:30:00.892+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-03-05T01:30:00.956+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=teste_dag, task_id=nvalido, execution_date=20230304T233000, start_date=20230305T013000, end_date=20230305T013000
[2023-03-05T01:30:01.023+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-03-05T01:30:01.067+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
