[2023-05-01T02:24:39.714+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: create_infra.create_table_bq scheduled__2023-04-30T00:00:00+00:00 [queued]>
[2023-05-01T02:24:39.740+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: create_infra.create_table_bq scheduled__2023-04-30T00:00:00+00:00 [queued]>
[2023-05-01T02:24:39.740+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T02:24:39.752+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-05-01T02:24:39.754+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-01T02:24:39.787+0000] {taskinstance.py:1300} INFO - Executing <Task(BigQueryExecuteQueryOperator): create_table_bq> on 2023-04-30 00:00:00+00:00
[2023-05-01T02:24:39.796+0000] {standard_task_runner.py:55} INFO - Started process 103 to run task
[2023-05-01T02:24:39.804+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'create_infra', 'create_table_bq', 'scheduled__2023-04-30T00:00:00+00:00', '--job-id', '550', '--raw', '--subdir', 'DAGS_FOLDER/create_infra.py', '--cfg-path', '/tmp/tmpqqr1khlj']
[2023-05-01T02:24:39.809+0000] {standard_task_runner.py:83} INFO - Job 550: Subtask create_table_bq
[2023-05-01T02:24:39.949+0000] {task_command.py:388} INFO - Running <TaskInstance: create_infra.create_table_bq scheduled__2023-04-30T00:00:00+00:00 [running]> on host da959356c36a
[2023-05-01T02:24:40.073+0000] {abstractoperator.py:613} ERROR - Exception rendering Jinja template for task 'create_table_bq', field 'sql'. Template: 'create_table_bq.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 606, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 657, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_table_bq.sql
[2023-05-01T02:24:40.078+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1374, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1493, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2115, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1179, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 606, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 657, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_table_bq.sql
[2023-05-01T02:24:40.101+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=create_infra, task_id=create_table_bq, execution_date=20230430T000000, start_date=20230501T022439, end_date=20230501T022440
[2023-05-01T02:24:40.127+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 550 for task create_table_bq (create_table_bq.sql; 103)
[2023-05-01T02:24:40.174+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-05-01T02:24:40.201+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
