[2023-05-03T02:17:01.295+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: gsc_to_bq.ingest_dado scheduled__2023-04-30T00:00:00+00:00 [queued]>
[2023-05-03T02:17:01.391+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: gsc_to_bq.ingest_dado scheduled__2023-04-30T00:00:00+00:00 [queued]>
[2023-05-03T02:17:01.400+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-03T02:17:01.402+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-05-03T02:17:01.403+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-03T02:17:01.535+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): ingest_dado> on 2023-04-30 00:00:00+00:00
[2023-05-03T02:17:01.582+0000] {standard_task_runner.py:55} INFO - Started process 13300 to run task
[2023-05-03T02:17:01.611+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'gsc_to_bq', 'ingest_dado', 'scheduled__2023-04-30T00:00:00+00:00', '--job-id', '597', '--raw', '--subdir', 'DAGS_FOLDER/gcs_to_bq.py', '--cfg-path', '/tmp/tmp6nd2h5ss']
[2023-05-03T02:17:01.654+0000] {standard_task_runner.py:83} INFO - Job 597: Subtask ingest_dado
[2023-05-03T02:17:02.461+0000] {task_command.py:388} INFO - Running <TaskInstance: gsc_to_bq.ingest_dado scheduled__2023-04-30T00:00:00+00:00 [running]> on host da959356c36a
[2023-05-03T02:17:03.109+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Junior Lafuente
AIRFLOW_CTX_DAG_ID=gsc_to_bq
AIRFLOW_CTX_TASK_ID=ingest_dado
AIRFLOW_CTX_EXECUTION_DATE=2023-04-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-30T00:00:00+00:00
[2023-05-03T02:17:12.798+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/gcs_to_bq.py", line 29, in ingest_dados
    import gcsfs
ModuleNotFoundError: No module named 'gcsfs'
[2023-05-03T02:17:13.179+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=gsc_to_bq, task_id=ingest_dado, execution_date=20230430T000000, start_date=20230503T021701, end_date=20230503T021713
[2023-05-03T02:17:13.425+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 597 for task ingest_dado (No module named 'gcsfs'; 13300)
[2023-05-03T02:17:13.654+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-05-03T02:17:13.994+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
