[2023-03-11T00:15:00.636+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: ingestion_dados_postgres.insere_dados_table_ed_replica scheduled__2023-03-10T22:30:00+00:00 [queued]>
[2023-03-11T00:15:00.670+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: ingestion_dados_postgres.insere_dados_table_ed_replica scheduled__2023-03-10T22:30:00+00:00 [queued]>
[2023-03-11T00:15:00.670+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-11T00:15:00.673+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-11T00:15:00.674+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-11T00:15:00.761+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): insere_dados_table_ed_replica> on 2023-03-10 22:30:00+00:00
[2023-03-11T00:15:00.779+0000] {standard_task_runner.py:55} INFO - Started process 13957 to run task
[2023-03-11T00:15:00.785+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ingestion_dados_postgres', 'insere_dados_table_ed_replica', 'scheduled__2023-03-10T22:30:00+00:00', '--job-id', '189', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_dados_postgres.py', '--cfg-path', '/tmp/tmpe34g1ib2']
[2023-03-11T00:15:00.791+0000] {standard_task_runner.py:83} INFO - Job 189: Subtask insere_dados_table_ed_replica
[2023-03-11T00:15:01.009+0000] {task_command.py:388} INFO - Running <TaskInstance: ingestion_dados_postgres.insere_dados_table_ed_replica scheduled__2023-03-10T22:30:00+00:00 [running]> on host 9ff22fa0bca3
[2023-03-11T00:15:01.719+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingestion_dados_postgres
AIRFLOW_CTX_TASK_ID=insere_dados_table_ed_replica
AIRFLOW_CTX_EXECUTION_DATE=2023-03-10T22:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-10T22:30:00+00:00
[2023-03-11T00:15:01.733+0000] {sql.py:254} INFO - Executing: insert into tb_data_engineering_replica
select * from tb_data_engineering
where nivel = 'SPEC'
        
[2023-03-11T00:15:01.814+0000] {base.py:73} INFO - Using connection ID 'postgres-***' for task execution.
[2023-03-11T00:15:02.990+0000] {base.py:73} INFO - Using connection ID 'postgres-***' for task execution.
[2023-03-11T00:15:03.344+0000] {sql.py:375} INFO - Running statement: insert into tb_data_engineering_replica
select * from tb_data_engineering
where nivel = 'SPEC'
        , parameters: None
[2023-03-11T00:15:03.447+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "tb_data_engineering_replica" does not exist
LINE 1: insert into tb_data_engineering_replica
                    ^

[2023-03-11T00:15:03.562+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=ingestion_dados_postgres, task_id=insere_dados_table_ed_replica, execution_date=20230310T223000, start_date=20230311T001500, end_date=20230311T001503
[2023-03-11T00:15:03.702+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 189 for task insere_dados_table_ed_replica (relation "tb_data_engineering_replica" does not exist
LINE 1: insert into tb_data_engineering_replica
                    ^
; 13957)
[2023-03-11T00:15:03.978+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-11T00:15:04.068+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
