[2023-05-03T23:47:43.978+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: gsc_to_bq.ingest_dado scheduled__2023-05-02T00:00:00+00:00 [queued]>
[2023-05-03T23:47:43.996+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: gsc_to_bq.ingest_dado scheduled__2023-05-02T00:00:00+00:00 [queued]>
[2023-05-03T23:47:43.996+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-03T23:47:43.998+0000] {taskinstance.py:1280} INFO - Starting attempt 80 of 81
[2023-05-03T23:47:43.998+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-03T23:47:44.023+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): ingest_dado> on 2023-05-02 00:00:00+00:00
[2023-05-03T23:47:44.032+0000] {standard_task_runner.py:55} INFO - Started process 6876 to run task
[2023-05-03T23:47:44.037+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'gsc_to_bq', 'ingest_dado', 'scheduled__2023-05-02T00:00:00+00:00', '--job-id', '721', '--raw', '--subdir', 'DAGS_FOLDER/gcs_to_bq.py', '--cfg-path', '/tmp/tmpao8fhgqd']
[2023-05-03T23:47:44.041+0000] {standard_task_runner.py:83} INFO - Job 721: Subtask ingest_dado
[2023-05-03T23:47:44.190+0000] {task_command.py:388} INFO - Running <TaskInstance: gsc_to_bq.ingest_dado scheduled__2023-05-02T00:00:00+00:00 [running]> on host 23a1495f3fb6
[2023-05-03T23:47:44.315+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Junior Lafuente
AIRFLOW_CTX_DAG_ID=gsc_to_bq
AIRFLOW_CTX_TASK_ID=ingest_dado
AIRFLOW_CTX_EXECUTION_DATE=2023-05-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=80
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-02T00:00:00+00:00
[2023-05-03T23:47:46.215+0000] {logging_mixin.py:137} INFO - Table(TableReference(DatasetReference('semiotic-joy-379201', 'venda'), 'tb_vendas'))
[2023-05-03T23:47:46.216+0000] {logging_mixin.py:137} INFO - [{'name': 'ID_MARCA', 'type': 'INTEGER'}, {'name': 'MARCA', 'type': 'STRING'}, {'name': 'ID_LINHA', 'type': 'INTEGER'}, {'name': 'LINHA', 'type': 'STRING'}, {'name': 'DATA_VENDA', 'type': 'DATE'}, {'name': 'QTD_VENDA', 'type': 'INTEGER'}]
[2023-05-03T23:47:46.339+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/registry.py", line 243, in get_filesystem_class
    register_implementation(protocol, _import_class(bit["class"]))
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/registry.py", line 266, in _import_class
    mod = importlib.import_module(mod)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'gcsfs'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/gcs_to_bq.py", line 49, in ingest_dados
    df = pd.read_excel(f"gs://bucket_raw_jr/input/Base 2017.xlsx")
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 364, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 1192, in __init__
    content_or_path=path_or_buffer, storage_options=storage_options
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 1071, in inspect_excel_format
    content_or_path, "rb", storage_options=storage_options, is_text=False
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 614, in get_handle
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 359, in _get_filepath_or_buffer
    filepath_or_buffer, mode=fsspec_mode, **(storage_options or {})
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/core.py", line 450, in open
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/core.py", line 280, in open_files
    expand=expand,
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/core.py", line 621, in get_fs_token_paths
    cls = get_filesystem_class(protocol)
  File "/home/airflow/.local/lib/python3.7/site-packages/fsspec/registry.py", line 245, in get_filesystem_class
    raise ImportError(bit["err"]) from e
ImportError: Please install gcsfs to access Google Storage
[2023-05-03T23:47:46.387+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=gsc_to_bq, task_id=ingest_dado, execution_date=20230502T000000, start_date=20230503T234743, end_date=20230503T234746
[2023-05-03T23:47:46.463+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 721 for task ingest_dado (Please install gcsfs to access Google Storage; 6876)
[2023-05-03T23:47:46.506+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-05-03T23:47:46.563+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
