[2023-05-03T02:24:58.642+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: gsc_to_bq.ingest_dado scheduled__2023-05-02T00:00:00+00:00 [queued]>
[2023-05-03T02:24:58.672+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: gsc_to_bq.ingest_dado scheduled__2023-05-02T00:00:00+00:00 [queued]>
[2023-05-03T02:24:58.673+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-03T02:24:58.674+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2023-05-03T02:24:58.674+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-03T02:24:58.715+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): ingest_dado> on 2023-05-02 00:00:00+00:00
[2023-05-03T02:24:58.730+0000] {standard_task_runner.py:55} INFO - Started process 13730 to run task
[2023-05-03T02:24:58.735+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'gsc_to_bq', 'ingest_dado', 'scheduled__2023-05-02T00:00:00+00:00', '--job-id', '602', '--raw', '--subdir', 'DAGS_FOLDER/gcs_to_bq.py', '--cfg-path', '/tmp/tmp590y1q1o']
[2023-05-03T02:24:58.743+0000] {standard_task_runner.py:83} INFO - Job 602: Subtask ingest_dado
[2023-05-03T02:24:58.980+0000] {task_command.py:388} INFO - Running <TaskInstance: gsc_to_bq.ingest_dado scheduled__2023-05-02T00:00:00+00:00 [running]> on host da959356c36a
[2023-05-03T02:24:59.283+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Junior Lafuente
AIRFLOW_CTX_DAG_ID=gsc_to_bq
AIRFLOW_CTX_TASK_ID=ingest_dado
AIRFLOW_CTX_EXECUTION_DATE=2023-05-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-02T00:00:00+00:00
[2023-05-03T02:25:00.791+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/gcs_to_bq.py", line 29, in ingest_dados
    import gcsfs
ModuleNotFoundError: No module named 'gcsfs'
[2023-05-03T02:25:00.830+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=gsc_to_bq, task_id=ingest_dado, execution_date=20230502T000000, start_date=20230503T022458, end_date=20230503T022500
[2023-05-03T02:25:00.891+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 602 for task ingest_dado (No module named 'gcsfs'; 13730)
[2023-05-03T02:25:00.951+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-05-03T02:25:01.042+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
