[2023-03-11T00:29:17.870+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: ingestion_dados_postgres.criar_tabela_ed_replica manual__2023-03-11T00:14:53.020433+00:00 [queued]>
[2023-03-11T00:29:17.896+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: ingestion_dados_postgres.criar_tabela_ed_replica manual__2023-03-11T00:14:53.020433+00:00 [queued]>
[2023-03-11T00:29:17.897+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-11T00:29:17.899+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2023-03-11T00:29:17.900+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-11T00:29:17.955+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): criar_tabela_ed_replica> on 2023-03-11 00:14:53.020433+00:00
[2023-03-11T00:29:17.969+0000] {standard_task_runner.py:55} INFO - Started process 14912 to run task
[2023-03-11T00:29:17.976+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ingestion_dados_postgres', 'criar_tabela_ed_replica', 'manual__2023-03-11T00:14:53.020433+00:00', '--job-id', '206', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_dados_postgres.py', '--cfg-path', '/tmp/tmpxga2sc75']
[2023-03-11T00:29:17.978+0000] {standard_task_runner.py:83} INFO - Job 206: Subtask criar_tabela_ed_replica
[2023-03-11T00:29:18.111+0000] {task_command.py:388} INFO - Running <TaskInstance: ingestion_dados_postgres.criar_tabela_ed_replica manual__2023-03-11T00:14:53.020433+00:00 [running]> on host 9ff22fa0bca3
[2023-03-11T00:29:18.236+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingestion_dados_postgres
AIRFLOW_CTX_TASK_ID=criar_tabela_ed_replica
AIRFLOW_CTX_EXECUTION_DATE=2023-03-11T00:14:53.020433+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-11T00:14:53.020433+00:00
[2023-03-11T00:29:18.238+0000] {sql.py:254} INFO - Executing: create table if not exists tb_data_engineering_replica(
    id int generated by default as identity,
    name varchar not null,
    cargo varchar not null,
    nivel varchar not null,
    dt date
)
[2023-03-11T00:29:18.254+0000] {base.py:73} INFO - Using connection ID 'postgres-***' for task execution.
[2023-03-11T00:29:18.628+0000] {base.py:73} INFO - Using connection ID 'postgres-***' for task execution.
[2023-03-11T00:29:18.698+0000] {sql.py:375} INFO - Running statement: create table if not exists tb_data_engineering_replica(
    id int generated by default as identity,
    name varchar not null,
    cargo varchar not null,
    nivel varchar not null,
    dt date
), parameters: None
[2023-03-11T00:29:18.758+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(tb_data_engineering_replica_id_seq, 2200) already exists.

[2023-03-11T00:29:18.781+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=ingestion_dados_postgres, task_id=criar_tabela_ed_replica, execution_date=20230311T001453, start_date=20230311T002917, end_date=20230311T002918
[2023-03-11T00:29:18.816+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 206 for task criar_tabela_ed_replica (duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(tb_data_engineering_replica_id_seq, 2200) already exists.
; 14912)
[2023-03-11T00:29:18.967+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-11T00:29:19.041+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
